version: '3'

services:
  app:
    container_name: crew-app
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    working_dir: /app
    volumes:
      - ./:/app
    command: ['php', '-S', '0.0.0.0:8000']
    ports:
      - "8000:8000"
    networks:
      - crew-network

  elasticsearch:
    container_name: crew-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - CLI_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
    networks:
      - crew-network

  kibana:
    container_name: crew-kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - "5601:5601"
    networks:
      - crew-network

networks:
  crew-network: {}
